export async function preloadTemplates() {
	const templatePaths = [
		// Add paths to "modules/midi-qol-rotv/templates"
		"modules/midi-qol-rotv/templates/actorOnUseMacrosConfig.html",
		"modules/midi-qol-rotv/templates/attack-roll.html",
		"modules/midi-qol-rotv/templates/bonus-damage-roll.html",
		"modules/midi-qol-rotv/templates/config.html",
		"modules/midi-qol-rotv/templates/damage-results.html",
		"modules/midi-qol-rotv/templates/damage-results-player.html",
		// "modules/midi-qol-rotv/templates/damage-results-v3.html",
		"modules/midi-qol-rotv/templates/damage-roll.html",
		"modules/midi-qol-rotv/templates/damage-roll-dialog.hbs",
		"modules/midi-qol-rotv/templates/dialog.html",
		"modules/midi-qol-rotv/templates/hits.html",
		"modules/midi-qol-rotv/templates/item-card-buttons.html",
		"modules/midi-qol-rotv/templates/item-card.hbs",
		"modules/midi-qol-rotv/templates/itemProperties.html",
		"modules/midi-qol-rotv/templates/itemTypeSelector.html",
		"modules/midi-qol-rotv/templates/midiPropertiesForm.hbs",
		"modules/midi-qol-rotv/templates/other-damage-roll.html",
		"modules/midi-qol-rotv/templates/roll.html",
		"modules/midi-qol-rotv/templates/roll-base.html",
		"modules/midi-qol-rotv/templates/roll-dialog.hbs",
		"modules/midi-qol-rotv/templates/rolloptions.html",
		"modules/midi-qol-rotv/templates/roll-stats.html",
		"modules/midi-qol-rotv/templates/rolloptions.html",
		"modules/midi-qol-rotv/templates/saves.html",
		"modules/midi-qol-rotv/templates/sound-config.html",
		"modules/midi-qol-rotv/templates/targetConfirmationConfig.html",
		"modules/midi-qol-rotv/templates/targetConfirmation.html",
		"modules/midi-qol-rotv/templates/tooltip.html",
		"modules/midi-qol-rotv/templates/tool-card.html",
		"modules/midi-qol-rotv/templates/troubleShooter.html",
		"modules/midi-qol-rotv/templates/undo-workflow.html"
	];
	return loadTemplates(templatePaths);
}
/*    "modules/midi-qol-rotv/templates/saves.html",
	"modules/midi-qol-rotv/templates/hits.html",
	"modules/midi-qol-rotv/templates/item-card.html",
	"modules/midi-qol-rotv/templates/tool-card.html",
	"modules/midi-qol-rotv/templates/config.html",
	"modules/midi-qol-rotv/templates/damage-results.html",
	"modules/midi-qol-rotv/templates/roll-stats.html",
	"modules/midi-qol-rotv/templates/damage-results-player.html",
	"modules/midi-qol-rotv/templates/targetConfirmation.html",
	// "modules/midi-qol-rotv/templates/midiProperties.html"
	"modules/midi-qol-rotv/templates/sound-config.html",
	"modules/midi-qol-rotv/templates/rollAlternate.html",
	"modules/midi-qol-rotv/templates/actorOnUseMacrosConfig.html",
	"modules/midi-qol-rotv/templates/dialog.html",
	"modules/midi-qol-rotv/templates/rollStatsConfig.html",
	"modules/midi-qol-rotv/templates/TargetConfirmationConfig.html",
	"modules/midi-qol-rotv/templates/rollStats.html",
	*/ 
